### ISSUE TITLE
请教大佬一个问题，如何对Flutter中Text进行光标选择呀？

### ISSUE THREAD

**Issue by liompei** [canhuah/WanAndroid#10]
请教大佬一个问题，如何对Flutter中Text进行光标选择呀？

**Comment by canhuah** [comment]
进行光标选择是什么意思？长按就可以选择啊 ，先选择全部，然后会有左右两个光标，自己拖。。。

**Comment by liompei** [comment]
https://github.com/flutter/flutter/issues/5422  问题是这样的，长按非输入的文字，无法选择，在Android原生中可以指定TextView的textIsSelectable="true"设置文字可选，但Flutter目前我还没看到解决方法，求大佬告知

**Comment by canhuah** [comment]
Flutter中的Text是StatelessWidget，并且里面没有任何的手势处理的，所以单纯的Text是无法实现你说的效果。 可以参考一下你发的issue中链接的做法
https://github.com/CalebQ42/CustomDiceRoller
