### ISSUE TITLE
点击run无法运行

### ISSUE THREAD

**Issue by xuhaifeng0705** [canhuah/WanAndroid#12]
下载了您的项目想运行，但是点击run按钮后报错执行不了。
![321829BC-0791-4152-BF51-812EBF6BF36C](https://user-images.githubusercontent.com/20841724/61839166-212b8e80-aebf-11e9-8bbe-4e0bc07f7e72.png)

**Comment by canhuah** [comment]
这个好像是mac的权限问题。。
