### ISSUE TITLE
升级后无法运行

### ISSUE THREAD

**Issue by chenjiaren145** [canhuah/WanAndroid#14]
![输出日志](https://user-images.githubusercontent.com/23132601/71065582-7046c880-21ac-11ea-85d8-36457ade2da6.png)

**Comment by canhuah** [comment]
![0B5A4273-9A7B-40B7-A1BD-6872EBD4892D](https://user-images.githubusercontent.com/19891586/71102584-b6734a80-21f3-11ea-8109-893df63e2562.png)

**Comment by canhuah** [comment]
找到android/app/src/main/AndroidMainifest.xml文件
第二行加入下面的代码
 xmlns:tools="http://schemas.android.com/tools"
第16行  <application后面加入下面代码
        tools:replace="android.app.AppComponentFactory"

**Comment by chenjiaren145** [comment]
<img width="1092" alt="QQ20191219-111447@2x" src="https://user-images.githubusercontent.com/23132601/71141963-d2590980-2250-11ea-9e43-5144a3315c42.png">
还是有问题

**Comment by canhuah** [comment]
加我qq吧719217980。。头疼
