### ISSUE TITLE
README link issue

### ISSUE THREAD

**Issue by Cygra** [canhuah/WanAndroid#15]
REAME 里博客的链接应该是 http://www.canhuah.com/2018/06/14/Flutter%E5%AE%9E%E6%88%98%E4%B9%8BWanAndroid%E9%A1%B9%E7%9B%AE%E4%B8%AD%E7%A2%B0%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98/

**Comment by canhuah** [comment]
@Cygra    感谢 现在才有空更新下链接
