### ISSUE TITLE
为什么我的界面加载不出图片？

### ISSUE THREAD

**Issue by RedSevenMale** [canhuah/WanAndroid#2]
Widget image = new Image.asset(
      'images/ic_launcher_round.png',
      width: 100.0,
      height: 100.0,
    );

**Comment by canhuah** [comment]
参考我的pubsper.yaml文件   ，该图片需要先引入，你可能缺少下面的代码  @DengShao

  assets:
    - images/ic_launcher_round.png

**Comment by RedSevenMale** [comment]
assets:
 - images/ic_launcher_round.png
 - images/logo.png
都有，我引入别的图片还是没有

**Comment by RedSevenMale** [comment]
![default](https://user-images.githubusercontent.com/39144187/44256516-f4491300-a23b-11e8-990d-00a9af2b6d8f.png)

**Comment by canhuah** [comment]
方便的话加我qq  719217980我看看
