### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by jackandroid2016** [canhuah/WanAndroid#5]
Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
  D:\WanAndroid-Flutter-master\WanAndroid-Flutter-master\lib\http\HttpUtilWithCookie.dart
...refers, in an import, to the following library:
  package:http/http.dart
That library is in a package that is not known. Maybe you forgot to mention it in your pubspec.yaml file?

**Comment by canhuah** [comment]
已更新
