### ISSUE TITLE
二维码过期了

### ISSUE THREAD

**Issue by forEveryDay** [canhuah/WanAndroid#6]

**Comment by canhuah** [comment]
蒲公英有一个月的时间限制 我晚上全面更新一下 
  你也可以把项目下载下来自己试试打包哈

**Comment by forEveryDay** [comment]
> 蒲公英有一个月的时间限制 我晚上全面更新一下
> 你也可以把项目下载下来自己试试打包哈

好的，谢谢啦，更新才是重点咯！才开始学习，还没来得及打包自己试

**Comment by canhuah** [comment]
已经更新好啦
