### ISSUE TITLE
关于用户的问题

### ISSUE THREAD

**Issue by lhyocean** [canhuah/WanAndroid#7]
我想问下，登录完成后，是有用户信息了，
然后我看你demo 收藏与取消收藏网络请求时都没有传用户的id等相关信息，请问下如何区别不同用户的收藏与取消收藏的

**Comment by lhyocean** [comment]
明白了，你是登录后保存cookie了。。。。

**Comment by canhuah** [comment]
实际上这些用户信息在cookie中，可以用作区别用户。在HttpUtilWithCookie.dart中可以看到有cookie相关的存取操作，不过写的有些不够优雅哈。。 关于Http请求的你也可以使用 Dio的库 
[https://github.com/flutterchina/dio](dio)
