### ISSUE TITLE
我想请问一下这两个封装类HttpUtil和HttpUtilwithCookie的区别是什么呢

### ISSUE THREAD

**Issue by yuyingjian123** [canhuah/WanAndroid#8]
作为新手对于这个项目还有一些疑问，可以给一个联系方式联系您吗

**Comment by yuyingjian123** [comment]
还有loginevent这个空白类的作用是什么呢？

**Comment by canhuah** [comment]
1. HttpUtil不带Cookie设置，HttpUtilwithCookie带了cookie信息，可以查看一下HttpUtilwithCookie类的79行和115行。项目中实际用的HttpUtilwithCookie。
2.LoginEvent类是一个登录消息事件，在登录成功的时候EventBus发送了这个消息事件，订阅了此消息的地方会有数据改变处理的逻辑。可以查看MyInfoPage类的27行左右。
3.我的QQ是719217980，添加时麻烦备注一下github哈

**Comment by yuyingjian123** [comment]
好的，感谢你的回答。已申请好友
